import type { InsuranceRuleSet } from './rule-set.js';

export const RULE_SET_V1: InsuranceRuleSet = {
  version: 'northstar-home-eu-v1',
  label: 'Northstar Standard European Home Policy v1.0',
  effectiveFrom: '2026-01-01T00:00:00Z',
  supportedCountries: ['FR', 'ES', 'PT', 'DE', 'IT'],
  baseAnnualRates: {
    FR: 180.00,
    ES: 160.00,
    PT: 145.00,
    DE: 195.00,
    IT: 175.00
  },
  propertyMultipliers: {
    apartment: 0.90,
    terraced_house: 1.05,
    semi_detached: 1.15,
    detached_house: 1.30,
    villa: 1.60
  },
  occupancyMultipliers: {
    owner_occupied: 1.00,
    tenant: 0.85,
    landlord: 0.95
  },
  areaMultipliers: {
    under_50_sqm: 0.80,
    '50_100_sqm': 1.00,
    '101_150_sqm': 1.25,
    '151_250_sqm': 1.55,
    over_250_sqm: 1.95
  },
  constructionYearMultipliers: {
    post_2015: 0.95,
    '2000_2015': 1.00,
    '1970_1999': 1.15,
    pre_1970: 1.30
  },
  claimsMultipliers: {
    0: 1.00,
    1: 1.20,
    2: 1.50,
    3: 1.90
  },
  coverageTierMultipliers: {
    essential: 0.80,
    comfort: 1.00,
    premium: 1.40
  },
  deductibleDiscounts: {
    150: 0.00,
    300: 25.00,
    500: 55.00,
    1000: 110.00
  },
  taxRates: {
    FR: 0.18, // 18% insurance tax
    ES: 0.14,
    PT: 0.15,
    DE: 0.19,
    IT: 0.21
  },
  maxClaimsForInstantQuote: 3,
  mandatoryDisclosure: 'DISCLOSURE: This is an indicative, non-binding quote generated by Northstar Home Insurance EU demonstration system. Premiums are deterministic based on declared risk factors under rule version northstar-home-eu-v1. Actual coverage binding requires formal policy underwriting and identity verification.'
};
