import type { InsuranceRuleSet } from "./rule-set.js";

export const RULE_SET_V2: InsuranceRuleSet = {
  version: "northstar-home-eu-v2",
  label: "Northstar Standard European Home Policy v2.0 (Updated 2026 Q3)",
  effectiveFrom: "2026-07-01T00:00:00Z",
  supportedCountries: ["FR", "ES", "PT", "DE", "IT"],
  baseAnnualRates: {
    FR: 195.0,
    ES: 175.0,
    PT: 155.0,
    DE: 210.0,
    IT: 190.0,
  },
  propertyMultipliers: {
    apartment: 0.88,
    terraced_house: 1.05,
    semi_detached: 1.18,
    detached_house: 1.35,
    villa: 1.65,
  },
  occupancyMultipliers: {
    owner_occupied: 1.0,
    tenant: 0.85,
    landlord: 0.95,
  },
  areaMultipliers: {
    under_50_sqm: 0.8,
    "50_100_sqm": 1.0,
    "101_150_sqm": 1.25,
    "151_250_sqm": 1.6,
    over_250_sqm: 2.05,
  },
  constructionYearMultipliers: {
    post_2015: 0.9,
    "2000_2015": 1.0,
    "1970_1999": 1.2,
    pre_1970: 1.35,
  },
  claimsMultipliers: {
    0: 1.0,
    1: 1.25,
    2: 1.55,
    3: 2.0,
  },
  coverageTierMultipliers: {
    essential: 0.8,
    comfort: 1.0,
    premium: 1.45,
  },
  deductibleDiscounts: {
    150: 0.0,
    300: 30.0,
    500: 65.0,
    1000: 130.0,
  },
  taxRates: {
    FR: 0.18,
    ES: 0.14,
    PT: 0.15,
    DE: 0.19,
    IT: 0.21,
  },
  maxClaimsForInstantQuote: 3,
  mandatoryDisclosure:
    "DISCLOSURE: This is an indicative, non-binding quote generated by Northstar Home Insurance EU demonstration system under rule version northstar-home-eu-v2. Actual coverage binding requires formal policy underwriting and identity verification.",
};
